### ISSUE TITLE
Remote addresses from server channels do not make sense

### ISSUE THREAD

**Issue by astei** [netty/netty-incubator-transport-io_uring#10]
Using Netty 4.1.54.Final and 0.0.1.Final of the io_uring transport. I am connecting to a server using TCP listening on a io_uring event loop, but it reports nonsensical remote addresses like `8000:bc:307f:0:0:0:0:0%37` (I was really connected from the IPv4 loopback address `127.0.0.1`) and `8000:84:e17f:0:2829:4c69:6f2f:6e65%37` (I was really connected from the IPv6 loopback address `::1`). These issues don't appear with the traditional epoll event loop.

`uname -a` reports `Linux fortitude 5.9.8-200.fc33.x86_64 #1 SMP Tue Nov 10 21:58:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`, so I'm on a kernel version that should work. I am using Java 11.0.9 to run the server.

**Comment by normanmaurer** [comment]
@astei sounds like a bug... I will have a look later this week.

**Comment by hugmanrique** [comment]
Probably has to do something with https://github.com/netty/netty-incubator-transport-io_uring/blob/main/src/main/java/io/netty/incubator/channel/uring/IOUringServerSocketChannel.java#L39?

**Comment by igor-lukyanov** [comment]
Confirming the same problem with IPv4 addresses (server ip is hidden):
[id: 0xe04bc21f, L:/XX.XX.XX.XX:443 ! R:/0.0.0.0:0]
There are zeroes instead of real remote IP address.

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty-incubator-transport-io_uring/pull/17

**Comment by astei** [comment]
I just checked with #17. It's working beautifully now!

One behavioral difference I noticed is that IPv4-mapped IPv6 addresses differ from what is shown with epoll - I am now getting the IPv6 address `/0:0:0:0:0:ffff:7f00:1%0` instead. I don't know if this is a bug or not, since otherwise everything is working.

**Comment by normanmaurer** [comment]
@astei I guess generally speaking its ok but I guess it would be best to have epoll / io_uring be more consistent here. Can you fill another issue ?

**Comment by astei** [comment]
Filed #18 for the IPv4-mapped IPv6 address nit.
