### ISSUE TITLE
version 0.0.6 on maven central 

### ISSUE THREAD

**Issue by QIvan** [netty/netty-incubator-transport-io_uring#105]
Hi! 
First of all, thank you very much for this library, I tried it on our workloads and it shows very nice results! 

I noticed you released version 0.0.6 but on maven central [only 0.0.5 is available](https://search.maven.org/artifact/io.netty.incubator/netty-incubator-transport-native-io_uring). Is it possible to publish an artefact with 0.0.6 version over there? 
For more details see this issue https://github.com/lettuce-io/lettuce-core/issues/1786

Thanks

**Comment by NiteshKant** [comment]
Hmm this is strange as the release build did upload artifacts to sonatype. @normanmaurer any idea what went wrong?

**Comment by normanmaurer** [comment]
hmm.. no.. Let me just trigger another release

**Comment by normanmaurer** [comment]
@NiteshKant @QIvan it did turn out our release workflow did not set the right property:

https://github.com/netty/netty-incubator-transport-io_uring/commit/5a7a11fa837cea440ad39ca7099bcf32ded50116

I did cut 0.0.7 and ensured it is released.

**Comment by izemlyanskiy** [comment]
wonderful, thanks @normanmaurer!
So, correct me if i'm wrong, the version 0.0.6 will be kinda skipped and we can expect 0.0.7 on maven central in near future, right?

**Comment by normanmaurer** [comment]
@izemlyanskiy yes... it is already on maven central:

https://repo1.maven.org/maven2/io/netty/incubator/netty-incubator-transport-native-io_uring/0.0.7.Final/
