### ISSUE TITLE
centos 8.4-Kernel: 4.18, it throwed " failed to load the required native library"

### ISSUE THREAD

**Issue by jammyMarse** [netty/netty-incubator-transport-io_uring#109]
i passed all tests of "the netty-incubator-transport-io_uring", but it still throwed exceptions.

<img width="1272" alt="wecom-temp-9219c48d593911754dcb11af7f4b66b8" src="https://user-images.githubusercontent.com/8069551/127639834-e49e6388-d8f9-48a6-9745-2f2c14094676.png">

**Comment by normanmaurer** [comment]
Kernel 4.18 is not recent enough. You need 5.9+
