### ISSUE TITLE
Tests doesn't seem to run using mvn 3.8.1

### ISSUE THREAD

**Issue by franz1981** [netty/netty-incubator-transport-io_uring#123]
I cannot find a way to make tests to run, probably I've missed something obvious

**Comment by 1Jo1** [comment]
I tried git bisect, this commit [Upgrade to Junit 5](https://github.com/netty/netty-incubator-transport-io_uring/commit/2ab49f6ad4f5f82a2e480f3d3d2954bac23f57e6) causes this issue

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty-incubator-transport-io_uring/pull/124... Thanks for reporting

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty-incubator-transport-io_uring/pull/124
