### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by xtuyaowu** [netty/netty-incubator-transport-io_uring#133]
hi:
   change from
          <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.42.Final</version>
        </dependency>
        to
        <dependency>
            <groupId>io.netty.incubator</groupId>
            <artifactId>netty-incubator-transport-native-io_uring</artifactId>
            <version>0.0.9.Final</version>
            <classifier>linux-x86_64</classifier>
        </dependency>

got lots of error such as missing

import io.netty.handler.codec.http.FullHttpResponse;
import io.netty.handler.codec.http.websocketx.CloseWebSocketFrame;
import io.netty.handler.codec.http.websocketx.ContinuationWebSocketFrame;
import io.netty.handler.codec.http.websocketx.PingWebSocketFrame;
import io.netty.handler.codec.http.websocketx.PongWebSocketFrame;
import io.netty.handler.codec.http.websocketx.TextWebSocketFrame;
import io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker;
import io.netty.handler.codec.http.websocketx.WebSocketFrame;
import io.netty.handler.codec.http.websocketx.WebSocketHandshakeException;

my questions is how to replace netty-all
thanks 
Best Regards

**Comment by chrisvest** [comment]
Try upgrading to netty version 4.1.70, and netty-incubator-transport-native-io_uring version 0.0.10.

**Comment by xtuyaowu** [comment]
question is : need use both netty version 4.1.70, and netty-incubator-transport-native-io_uring version 0.0.10. ？

**Comment by xtuyaowu** [comment]
solved thanks @chrisvest
