### ISSUE TITLE
Memory is not reclaimed after death of a process

### ISSUE THREAD

**Issue by igor-lukyanov** [netty/netty-incubator-transport-io_uring#14]
When we run an app that uses io_uring, and then gracefully shutdown it - all following attempts to start it again fail because of OOM. Looks like shared buffers are not reclaimed when an app exits.  

/proc/meminfo reports before and after are below.
Please look at Mapped and Shmem metrics.

Before:
```
MemTotal:        4026908 kB
MemFree:         2939452 kB
MemAvailable:    2929140 kB
Buffers:           13132 kB
Cached:           795416 kB
SwapCached:            0 kB
Active:            65104 kB
Inactive:         941052 kB
Active(anon):        448 kB
Inactive(anon):   824480 kB
Active(file):      64656 kB
Inactive(file):   116572 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              5608 kB
Writeback:             0 kB
AnonPages:        197620 kB
Mapped:           563324 kB
Shmem:            627224 kB
KReclaimable:      23108 kB
Slab:              41216 kB
SReclaimable:      23108 kB
SUnreclaim:        18108 kB
KernelStack:        2784 kB
PageTables:         4432 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2013452 kB
Committed_AS:    1088240 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       13560 kB
VmallocChunk:          0 kB
Percpu:             1120 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:       77796 kB
DirectMap2M:     4116480 kB
```

After: 
```
MemTotal:        4026908 kB
MemFree:           87072 kB
MemAvailable:          0 kB
Buffers:            1912 kB
Cached:          2835300 kB
SwapCached:            0 kB
Active:            67296 kB
Inactive:        3619632 kB
Active(anon):      59276 kB
Inactive(anon):  3611160 kB
Active(file):       8020 kB
Inactive(file):     8472 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 4 kB
Writeback:             0 kB
AnonPages:        849724 kB
Mapped:          2708828 kB
Shmem:           2820712 kB
KReclaimable:      28840 kB
Slab:              74780 kB
SReclaimable:      28840 kB
SUnreclaim:        45940 kB
KernelStack:        3952 kB
PageTables:        19856 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2013452 kB
Committed_AS:    3569584 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       14820 kB
VmallocChunk:          0 kB
Percpu:             1456 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      147428 kB
DirectMap2M:     4046848 kB
```

**Comment by normanmaurer** [comment]
Can you show all your code that is used ?

**Comment by igor-lukyanov** [comment]
Will write minimal reproducible example shortly, the app itself is quite big.

**Comment by normanmaurer** [comment]
@igor-lukyanov thanks a lot... Also if you can share any perf data (like before and after) I would be very interested :)

**Comment by normanmaurer** [comment]
@igor-lukyanov I tried to replicate this but without any luck. Please come back to me once you have a reproducer / more details. Please also include kernel version etc.

**Comment by igor-lukyanov** [comment]
It's from epoll: 

```
AbstractChannel$AnnotatedConnectException
connect(..) failed: Address family not supported by protocol: /[2a01:b740:a41:20c:0:0:0:e]:443
ConnectException
connect(..) failed: Address family not supported by protocol
io.netty.channel.unix.Errors in throwConnectException at line 124
io.netty.channel.unix.Socket in connect at line 239
io.netty.channel.epoll.AbstractEpollChannel in doConnect0 at line 736
io.netty.channel.epoll.AbstractEpollChannel in doConnect at line 721
io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe in connect at line 563
io.netty.channel.DefaultChannelPipeline$HeadContext in connect at line 1342
io.netty.channel.AbstractChannelHandlerContext in invokeConnect at line 548
io.netty.channel.AbstractChannelHandlerContext in connect at line 533
io.netty.channel.AbstractChannelHandlerContext in connect at line 517
io.netty.channel.DefaultChannelPipeline in connect at line 978
io.netty.channel.AbstractChannel in connect at line 253
io.netty.bootstrap.Bootstrap$3 in run at line 250
io.netty.util.concurrent.AbstractEventExecutor in safeExecute at line 164
io.netty.util.concurrent.SingleThreadEventExecutor in runAllTasks at line 472
io.netty.channel.epoll.EpollEventLoop in run at line 384
io.netty.util.concurrent.SingleThreadEventExecutor$4 in run at line 989
io.netty.util.internal.ThreadExecutorMap$2 in run at line 74
io.netty.util.concurrent.FastThreadLocalRunnable in run at line 30
java.lang.Thread in run at line 832
```

**Comment by igor-lukyanov** [comment]
It vanishes when trying to reproduce it in a simple app, still digging.

**Comment by normanmaurer** [comment]
Keep me posted

**Comment by normanmaurer** [comment]
Any update @igor-lukyanov  ?

**Comment by igor-lukyanov** [comment]
> Any update @igor-lukyanov ?

Sorry for the delay, will test today with different kernel/OS versions.

**Comment by igor-lukyanov** [comment]
Checked with kernel 5.9.10-050910-generic (vs 5.9.0-050900-generic where the bug was seen) and couldn't reproduce the issue. Digging further.

**Comment by igor-lukyanov** [comment]
Reproduced the issue under kernel version 5.9.10-050910-generic as well, after applying kill -9.
Mapped:           956236 kB
Shmem:            978976 kB
One important thing - 'port already in use' error occurs after trying to run app once again (previous process 100% does not exist by that time), so it seems some sockets/ports stay alive and retain associated buffers. So seems it's more on the side of application, not the library itself, though the cause can be be somehow related to https://github.com/netty/netty-incubator-transport-io_uring/issues/16

**Comment by normanmaurer** [comment]
I wonder if this is also related to https://github.com/netty/netty-incubator-transport-io_uring/pull/20

**Comment by igor-lukyanov** [comment]
> I wonder if this is also related to #20
Thank you, will check today w/ the fix.

**Comment by normanmaurer** [comment]
thanks a lot ...

**Comment by igor-lukyanov** [comment]
Checked, problem is still in place (though reveals itself only when the tested proxy app has some in-flight connections when getting stopped, idle start/stop works without problems with shmem). Will try to make MRE.

**Comment by igor-lukyanov** [comment]
8 hours passed since app was killed, checked `ss -nlp` output to find any sockets that can retain memory. Output attached (for 2 cases: when java process was dead and a moment later when it has been restarted and is running already).

What I'm finding strange is that a couple of udp and even tcp listening sockets stay alive even after the death of the app – all 3 udp listening sockets and 2 special purpose tcp sockets (with incoming local connections). 

UPD: Checked the code, found that udp channels were not closed properly by the app, but don't see any reasons why tcp channels stay alive after death of the app, looking into it further.

udp          UNCONN        0             0                                                127.0.0.1:1812                           0.0.0.0:*                                                                                                 
udp          UNCONN        0             0                                                127.0.0.1:1813                           0.0.0.0:*                                                                                                 
udp          UNCONN        0             0                                                  0.0.0.0:8484                           0.0.0.0:*                                                                                                 
tcp          LISTEN        0             4096                                               0.0.0.0:8080                           0.0.0.0:*                                                                                                 
tcp          LISTEN        0             4096                                             127.0.0.1:1980                           0.0.0.0:*      

[ss_with_java_running.txt](https://github.com/netty/netty-incubator-transport-io_uring/files/5610269/ss_with_java_running.txt)
[ss_after_death.txt](https://github.com/netty/netty-incubator-transport-io_uring/files/5610270/ss_after_death.txt)

**Comment by normanmaurer** [comment]
How you killed it ? Kill -9 ?

**Comment by normanmaurer** [comment]
@igor-lukyanov ping...

**Comment by normanmaurer** [comment]
I wonder if this is also related to that was reported here:

https://lore.kernel.org/io-uring/CAOKbgA66u15F+_LArHZFRuXU9KAiq_K0Ky2EnFSh6vRv23UzSw@mail.gmail.com/T/#u

**Comment by 1Jo1** [comment]
@normanmaurer @igor-lukyanov close this issue? :)

**Comment by normanmaurer** [comment]
Yes :) Thanks a lot!
