### ISSUE TITLE
netty io_uring was slower than epoll

### ISSUE THREAD

**Issue by xbzhang99** [netty/netty-incubator-transport-io_uring#152]
I collected some stats on x86, 5.13 kernel, using netty-incubator-iouring 13 with Cassandra 4.0. The network throughput is about 8% lower than netty epoll. The context switches is 69% higher than than epoll, and the interrupts are 2% higher than epoll. Also, CPI (circles per instruction) is 8% higher. 

<html>
<body>

  | iouring | epoll | diff |   |  
-- | -- | -- | -- | -- | --
load | 1000 | 1000 |   | Actual | Calculated
throughput | 142868 | 154465 | 1.081 | 8.1 | 11.4
util | 52.0 | 50.3 | 0.967 | -3.3 |  
freq | 3.09 | 3.13 | 1.013 | 1.3 |  
CPI | 1.33 | 1.22 | 0.915 | 8.5 |  
Pathlength (Kinstruction/throughput) | 842.7 | 801.6 | 0.951 | 4.9 |  

</body>
</html>

netty io_uring flamegraph
![iouring-read-cache-run002_profiler](https://user-images.githubusercontent.com/58006833/159762583-cfebb255-6a10-41b8-9f0e-96ef67a66a5e.svg)

netty epoll flamegraph
![epoll-read-cache-run002_profiler](https://user-images.githubusercontent.com/58006833/159762866-a3558844-7fe6-452d-bdcb-89af135562fe.svg)

**Comment by franz1981** [comment]
Please can you attache the flamegraphs or sending me via email?
I cannot navigate the flamegraphs in order to understand what's going on.
Looking at the flames in this form It doesn't seem and I/O bounded benchmark: if the system is not I/O bounded and Netty threads (thanks to io_uring) got to sleep faster, awaking them will cost more, cause more context switches etc etc
So please share a bit more about the test and data results

**Comment by xbzhang99** [comment]
Tests were done using READ.sh script in Cassandra.

IOuring:
./READ.sh 120 50
Results:
Op rate                   :  188,259 op/s  [simple1: 188,259 op/s]
Partition rate            :  188,259 pk/s  [simple1: 188,259 pk/s]
Row rate                  : 1,882,971 row/s [simple1: 1,882,971 row/s]
Latency mean              :    0.3 ms [simple1: 0.3 ms]
Latency median            :    0.2 ms [simple1: 0.2 ms]
Latency 95th percentile   :    0.3 ms [simple1: 0.3 ms]
Latency 99th percentile   :    0.5 ms [simple1: 0.5 ms]
Latency 99.9th percentile :    1.0 ms [simple1: 1.0 ms]
Latency max               :   55.6 ms [simple1: 55.6 ms]
Total partitions          : 22,778,788 [simple1: 22,778,788]
Total errors              :          0 [simple1: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:02:00

Epoll:
./READ.sh 120 50
Op rate                   :  204,277 op/s  [simple1: 204,277 op/s]
Partition rate            :  204,277 pk/s  [simple1: 204,277 pk/s]
Row rate                  : 2,042,924 row/s [simple1: 2,042,924 row/s]
Latency mean              :    0.2 ms [simple1: 0.2 ms]
Latency median            :    0.2 ms [simple1: 0.2 ms]
Latency 95th percentile   :    0.3 ms [simple1: 0.3 ms]
Latency 99th percentile   :    0.3 ms [simple1: 0.3 ms]
Latency 99.9th percentile :    0.9 ms [simple1: 0.9 ms]
Latency max               :   55.5 ms [simple1: 55.5 ms]
Total partitions          : 24,601,614 [simple1: 24,601,614]
Total errors              :          0 [simple1: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:02:00

Best regards,
Xubo

**Comment by xbzhang99** [comment]
Tests were done using READ.sh script in Cassandra (cassandra-stress).

IOuring:
./READ.sh 120 50
Results:
Op rate                   :  188,259 op/s  [simple1: 188,259 op/s]
Partition rate            :  188,259 pk/s  [simple1: 188,259 pk/s]
Row rate                  : 1,882,971 row/s [simple1: 1,882,971 row/s]
Latency mean              :    0.3 ms [simple1: 0.3 ms]
Latency median            :    0.2 ms [simple1: 0.2 ms]
Latency 95th percentile   :    0.3 ms [simple1: 0.3 ms]
Latency 99th percentile   :    0.5 ms [simple1: 0.5 ms]
Latency 99.9th percentile :    1.0 ms [simple1: 1.0 ms]
Latency max               :   55.6 ms [simple1: 55.6 ms]
Total partitions          : 22,778,788 [simple1: 22,778,788]
Total errors              :          0 [simple1: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:02:00

Epoll:
./READ.sh 120 50
Op rate                   :  204,277 op/s  [simple1: 204,277 op/s]
Partition rate            :  204,277 pk/s  [simple1: 204,277 pk/s]
Row rate                  : 2,042,924 row/s [simple1: 2,042,924 row/s]
Latency mean              :    0.2 ms [simple1: 0.2 ms]
Latency median            :    0.2 ms [simple1: 0.2 ms]
Latency 95th percentile   :    0.3 ms [simple1: 0.3 ms]
Latency 99th percentile   :    0.3 ms [simple1: 0.3 ms]
Latency 99.9th percentile :    0.9 ms [simple1: 0.9 ms]
Latency max               :   55.5 ms [simple1: 55.5 ms]
Total partitions          : 24,601,614 [simple1: 24,601,614]
Total errors              :          0 [simple1: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:02:00

**Comment by franz1981** [comment]
Thanks @xbzhang99 but please can you still attach somewhere the flamagraphs you've sent? sharing details of machines (not just OS), JVM etc etc

**Comment by xbzhang99** [comment]
it was jdk14. Sorry I can't seem to attach the flamegraphs (I already dragged and dropped them above)

**Comment by njhill** [comment]
@franz1981 try downloading the .svg files first and then open them in a browser from your local disk. If you just click on them directly the javascript is disabled.

**Comment by franz1981** [comment]
thanks @njhill :O I was thinking was just an image, not a svg :O
I apologize @xbzhang99

**Comment by franz1981** [comment]
@xbzhang99 I need few others info to better understand it

1. profiling duration
2. number of cores (logical too) of the machine
3. a profiler run using `-t` argument
4. the machine is physical?
5. how many physical event loops are created?

**Comment by xbzhang99** [comment]
tried several io.netty.iouring.iosqeAsyncThreshold values, but the client got timedout when it was >2
The machine was physical, has 64 cores. 
How to check #of Netty event loops?

**Comment by franz1981** [comment]
There are still missing answers, useful for the investigation:
- duration of profiling session ie the -d argument of async-profiler

> tried several io.netty.iouring.iosqeAsyncThreshold values, but the client got timedout when it was >2

Try with a number much higher then 25: how many connections are created against the Cassandra node?
You can bump it to be 2147483647

But I suggest first to consider the suggestion from @normanmaurer too first, on https://github.com/netty/netty-incubator-transport-io_uring/issues/106#issuecomment-876173958

> How to check #of Netty event loops?

It depends by Cassandra I think, can you share the GitHub link of the exact test? I am not familiar with Cassandra codebase

**Comment by xbzhang99** [comment]
I increased the value to 2000000000, and the client (cassandra-stress) gave:
com.datastax.driver.core.exceptions.OperationTimedOutException: [/134.134.101.101:9042] Timed out waiting for server response
java.util.NoSuchElementException

what is async-profiler?

**Comment by xbzhang99** [comment]
I reduced the threads as per https://github.com/netty/netty-incubator-transport-io_uring/issues/106#issuecomment-876173958.
The throughput is on par with epoll (also reduced to the same number of threads). And the context switches were also much lower.

So can we have a smaller default for the threads? Can we also make the number of threads a runtime parameter?

**Comment by franz1981** [comment]
@xbzhang99 because JNI to access the ring buffers has still a cost (many, TBH) but here thanks to unsafe (and VarHandle in the future) there's not need to pay that cost.

**Comment by xbzhang99** [comment]
I reduced the the number of threads for NioEventLoopGroup, and I got about the same throughput as Epoll and IOUring.

**Comment by normanmaurer** [comment]
@xbzhang99 also one important aspect is that io_uring only will give you improvements when you are IO heavy in terms of network sys calls atm. Also it will only show an big improvement when a lot of connections are doing IO that sit on the same `IOUringEventLoop`.

**Comment by xbzhang99** [comment]
> @xbzhang99 because JNI to access the ring buffers has still a cost (many, TBH) but here thanks to unsafe (and VarHandle in the future) there's not need to pay that cost.
@franz1981 
Could you explain more? I thought with both libring and io-uring API, you have to use jni to access the ring buffers?
what about unsafe?

**Comment by franz1981** [comment]
Nope, in the current version there's no need of JNI to access the iuring ring buffers

**Comment by franz1981** [comment]
Closing this as explained 😃
