### ISSUE TITLE
io_uring cannot allocate memory

### ISSUE THREAD

**Issue by artnaseef** [netty/netty-incubator-transport-io_uring#163]
In the FAQ:

```
$ ulimit -l
65536
```

I dug through all the layers to increase the memlock limit for a program running in a docker container.  Increased the limit to 1GB.  It still failed.

Thankfully, transitive dependency exclusion came to the rescue.

**Comment by chrisvest** [comment]
Do you run Docker with `--privileged`?

**Comment by artnaseef** [comment]
No

**Comment by chrisvest** [comment]
I've had to use `--privileged` when using io_uring inside a docker container (via Docker for Mac).

**Comment by chrisvest** [comment]
Closing because I think this is a docker issue, and not something we can fix in our io_uring integration.

**Comment by artnaseef** [comment]
Please re-open.  Please make the requirement to run privileged OPTIONAL and NOT DEFAULT.  This make the software hard to use for what benefit?  I don't even know.

**Comment by artnaseef** [comment]
Why is io_uring forced on?

**Comment by chrisvest** [comment]
It's a requirement of the io_uring system call APIs. The entire point of this repository is to provide an io_uring integration for Netty, but we're not forcing you to use io_uring. You can use epoll instead, or nio.

**Comment by artnaseef** [comment]
OK, I dug up the history on this one - haven't seen it in a while (thanks to adding the maven dependency exclusion).  Turns out there's an intermediate project that's pulling in this dependency, which leads to this problem.  That project really shouldn't be forcing io_uring on.

So I agree that this isn't a problem in the Netty, nor the io_uring module, itself.  With that said, it would be great if a search on the resulting error message lead to a page that explains the problem.  As a user of the intermediate project, I was not aware of how Netty, and io_uring support in Netty, comes into play.  The error message produced is obscure, and searches on that error message lead to mention of the need to run a privileged container - which doesn't help when running a priveleged container is bad.

Here's the resulting error message: "failed: Cannot allocate memory"

Perhaps I'll go hunt down those stackoverflow / discussions pages and add this info.

**Comment by artnaseef** [comment]
Actually, this is one of the first pages to come up: https://github.com/netty/netty-incubator-transport-io_uring

Can you add text in there to the effect, "removing this JAR file from the project can work-around this problem"?
