### ISSUE TITLE
Replace stdlib write/read with send/recv

### ISSUE THREAD

**Issue by franz1981** [netty/netty-incubator-transport-io_uring#165]
https://github.com/netty/netty/issues/12673 ditto as before

**Comment by franz1981** [comment]
@chrisvest this is still valid in the 'main` branch of the Netty repo right?

**Comment by chrisvest** [comment]
@franz1981 that version uses `recv` for reading, and `writev` for sending, but I suspect we'll soon change that `writev` to `sendmsg` - Norman has some ideas for changing the IO loops that will require that.

**Comment by franz1981** [comment]
@chrisvest on the pr for Netty 5 io_uring it seems it's using read/write and not recv/send (writev is for mutile writes, while here I mean for single one)

**Comment by franz1981** [comment]
For writev (on epoll) I didn't spot any improvement by using sendmsg, no idea if it still holds for io_uring in its recent iterations, but we can ask the io_uring folks to clarify that

**Comment by chrisvest** [comment]
The `recv` is here: https://github.com/netty/netty/blob/main/transport-classes-io_uring/src/main/java/io/netty5/channel/uring/AbstractIOUringChannel.java#L214-L215

We also use `read`, but only for the eventfd. Maybe that's what you saw.

**Comment by franz1981** [comment]
Uhm, very likely (I should not use the phone to read prs, bad habit, I apologize)!
