### ISSUE TITLE
IPv4-mapped IPv6 addresses are shown as IPv6 addresses when they should be shown as IPv4 ones

### ISSUE THREAD

**Issue by astei** [netty/netty-incubator-transport-io_uring#18]
Now that #10 is fixed I found a minor issue. More of a nit than anything.

IPv4-mapped IPv6 addresses differ from what is shown with epoll. For instance, consider the IPv4-mapped IPv6 address `:ffff:127.0.0.1`. In the epoll transport this is represented as just `127.0.0.1`, but with the io_uring transparent it shows as the IPv6 address `/0:0:0:0:0:ffff:7f00:1%0` instead.

**Comment by normanmaurer** [comment]
@astei can you check https://github.com/netty/netty-incubator-transport-io_uring/pull/21 ?

**Comment by astei** [comment]
I am celebrating the American Thanksgiving holiday - I'll check it next week when I have time.

**Comment by astei** [comment]
@normanmaurer that PR did not fix the issue.

**Comment by normanmaurer** [comment]
@astei interesting... can you show me how you bootstrap the server ?

**Comment by normanmaurer** [comment]
@astei I think I know what is wrong... Can you verify https://github.com/netty/netty-incubator-transport-io_uring/pull/24 ?
