### ISSUE TITLE
Problem with os.detected.arch on AARCH64

### ISSUE THREAD

**Issue by martin-g** [netty/netty-incubator-transport-io_uring#22]
I know that this library does not support AARCH64 at the moment but I tried to build it and see whether I can help supporting it.

Running `mvn clean package` starts with:

```
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: aarch_64
...
```

and later fails with:

```
[ERROR] Failed to execute goal on project netty-incubator-transport-native-io_uring: Could not resolve dependencies for project io.netty.incubator:netty-incubator-transport-native-io_uring:jar:0.0.2.Final-SNAPSHOT: Failure to find io.netty:netty-transport-native-unix-common:jar:linux-aarch_64:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
netty-transport-native-unix-common:4.1.54 **does** have a binary for aarch64 but there is no `_` in its classifier (`linux-aarch64`):

https://repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.1.54.Final/netty-transport-native-unix-common-4.1.54.Final-linux-aarch64.jar

I have no idea why os-maven-plugin puts this `_` in the arch name (https://github.com/trustin/os-maven-plugin/#property-osdetectedarch) but this leads to issues like this one and https://github.com/netty/netty-tcnative/issues/552.

**Comment by normanmaurer** [comment]
@trustin can you check why the plugin does this and if its a bug or not ?

**Comment by trustin** [comment]
It's not a bug but a convention. `<main_architecture>_<bitmode>` for consistency.

**Comment by trustin** [comment]
We can of course discuss about this and make a breaking change if it doesn't make much sense. :smile:

**Comment by martin-g** [comment]
The problem is in the inconsistency between the classifiers in the different Netty modules. Some use `aarch_64` and others `aarch64`. It seems some modules use `os.detected.arch` and others - `os.arch`.

**Comment by normanmaurer** [comment]
I am open to use whatever seems to be more correct...

**Comment by trustin** [comment]
Could Netty modules upload with `aarch_64` classifier, then?

**Comment by martin-g** [comment]
I was going to suggest to use `aarch64` (i.e. `os.arch`) because of two reasons:
1) it is more common (`uname -p`, Linux buildtools (aarch64-linux-gnu-...), etc.)
2) backward compatibility in old modules like `netty-transport-native-unix-common`

But this breaks for x86 systems. Java's `System.getProperty("os.arch")` returns `amd64` instead of `x86_64`.

So, I agree with @trustin that it would be better to use `os-maven-plugin` to _normalize_ the architectures (i.e. `aarch_64`). But this may lead to problems for the old modules which already use `os.arch`.

**Comment by normanmaurer** [comment]
@martin-g I guess as long as we update all of these together it should be fine...

**Comment by martin-g** [comment]
After upgrading my Ubuntu 20.04.1 to kernel 5.10-rc6 I was able to run all tests successfully on AARCH64!

I had to make 3 things:

1) Workaround the issue in this ticket with :

```
diff --git pom.xml pom.xml
index bd35fc8..53c620a 100644
--- pom.xml
+++ pom.xml
@@ -79,7 +79,7 @@
     <skipTests>true</skipTests>
     <netty.version>4.1.54.Final</netty.version>
     <netty.build.version>28</netty.build.version>
-    <jni.classifier>${os.detected.name}-${os.detected.arch}</jni.classifier>
+    <jni.classifier>${os.detected.name}-${os.arch}</jni.classifier>
   </properties>
 
   <build>
@@ -369,7 +369,7 @@
               <execution>
                 <id>build-native-lib</id>
                 <configuration>
-                  <name>netty_transport_native_io_uring_${os.detected.arch}</name>
+                  <name>netty_transport_native_io_uring_${os.arch}</name>
                   <nativeSourceDirectory>${nativeSourceDirectory}</nativeSourceDirectory>
                   <libDirectory>${project.build.outputDirectory}</libDirectory>
                   <!-- We use Maven's artifact classifier instead.
@@ -405,7 +405,7 @@
                       <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                     </manifest>
                     <manifestEntries>
-                      <Bundle-NativeCode>META-INF/native/libnetty_transport_native_io_uring_${os.detected.arch}.so; osname=Linux; processor=${os.detected.arch},*</Bundle-NativeCode>
+                      <Bundle-NativeCode>META-INF/native/libnetty_transport_native_io_uring_${os.arch}.so; osname=Linux; processor=${os.arch},*</Bundle-NativeCode>
                       <Automatic-Module-Name>${javaModuleName}</Automatic-Module-Name>
                     </manifestEntries>
                     <index>true</index>
```
2) manually make some symlinks:
```
ll target/native-build/target/lib/
total 2.0M
-rw-r--r-- 1 ubuntu ubuntu 1.9M Aug 21 11:19  libnetty_tcnative_linux_aarch64.so
lrwxrwxrwx 1 ubuntu ubuntu   34 Nov 30 13:14  libnetty_tcnative.so -> libnetty_tcnative_linux_aarch64.so
lrwxrwxrwx 1 ubuntu ubuntu   34 Nov 30 13:13 'libnetty_tcnative-@VERSION@.so' -> libnetty_tcnative_linux_aarch64.so
-rwxr-xr-x 1 ubuntu ubuntu  86K Nov 30 15:42  libnetty_transport_native_io_uring_aarch64-0.0.2.Final-SNAPSHOT.so*
-rwxr-xr-x 1 ubuntu ubuntu 1.4K Nov 30 15:42  libnetty_transport_native_io_uring_aarch64.la*
lrwxrwxrwx 1 ubuntu ubuntu   66 Nov 27 13:46  libnetty_transport_native_io_uring_aarch_64.so -> libnetty_transport_native_io_uring_aarch64-0.0.2.Final-SNAPSHOT.so*
lrwxrwxrwx 1 ubuntu ubuntu   66 Nov 30 15:42  libnetty_transport_native_io_uring_aarch64.so -> libnetty_transport_native_io_uring_aarch64-0.0.2.Final-SNAPSHOT.so*
lrwxrwxrwx 1 ubuntu ubuntu   66 Nov 27 13:45  libnetty_transport_native_io_uring.so -> libnetty_transport_native_io_uring_aarch64-0.0.2.Final-SNAPSHOT.so*
```

3) export `LD_LIBRARY_PATH` to `/home/ubuntu/git/netty/netty-incubator-transport-io_uring/target/native-build/target/lib`

and the result is:
```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 382, Failures: 0, Errors: 0, Skipped: 65
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:55 min
[INFO] Finished at: 2020-11-30T15:45:00Z
```

I hope this is useful to the other ARM64 users out there!
