### ISSUE TITLE
Add profile for cross-compile for aarch64

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-incubator-transport-io_uring#26]
Let's add a profile to be able to cross-compile for aarch64 the same as we do for other netty projects

**Comment by martin-g** [comment]
I'll give you a hand on this!
I'll send a PR later today!

**Comment by normanmaurer** [comment]
@martin-g let's see what we did in netty:

https://github.com/netty/netty/blob/4.1/docker/Dockerfile.cross_compile_aarch64
https://github.com/netty/netty/blob/4.1/docker/docker-compose.yaml#L44
