### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by HookWoods** [netty/netty-incubator-transport-io_uring#41]
Hello, this issue is linked to io_uring but not really netty but I would like to know if some of you could help me. I'm trying the io uring in a docker container, and when I start it, I got this error every time.

`
java.lang.RuntimeException: failed to create io_uring ring fd Operation not permitted
	at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method) ~[onefork.jar:git-OneFork-47e86db]
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:141) ~[onefork.jar:git-OneFork-47e86db]
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:174) ~[onefork.jar:git-OneFork-47e86db]
	at io.netty.incubator.channel.uring.IOUring.<clinit>(IOUring.java:36) ~[onefork.jar:git-OneFork-47e86db]
`

Without docker, the server starts normally but looks like Docker hasn't the permission and I can't find how to fix it. Thank you!

**Comment by normanmaurer** [comment]
Maybe its related to not be able to use mmap ? Can you try to run with `--privileged` and see if the problem still persist ? Also are you sure the kernel will be recent enough ?

**Comment by HookWoods** [comment]
Yup, it works with privileged thank you! But as you may understand, we can't use privileged args in our production server, it's a big security problem like root users

**Comment by normanmaurer** [comment]
Fully understand ... I just wanted to understand if it's related to this . You may need to do a bit more digging into what exactly you need to allow in docker to use io_uring. As you said it's not a netty issue

**Comment by normanmaurer** [comment]
@HookWoods this may be related to this:

https://github.com/moby/moby/issues/39396

**Comment by normanmaurer** [comment]
@HookWoods please update this issue once you found out more... This way we can also add this to the FAQ.

**Comment by HookWoods** [comment]
Yup, np. For the moment we use privileged args cause we want to try the io uring in beta but when we find more I will update this issue.

**Comment by HookWoods** [comment]
Ok, after an update of libseccomp, it finally works, looks like we weren't on the latest version. So the moby config file with the new lib works greats!

**Comment by normanmaurer** [comment]
@HookWoods would you be interested to add something to our FAQ section of the readme for this ? I suspect more and more people may want to use it with docker.
