### ISSUE TITLE
PollRemoveTest test failure

### ISSUE THREAD

**Issue by cmonkey** [netty/netty-incubator-transport-io_uring#5]
git commit 70d645a40f8c8cbe5f986218d68d388cd04d9e12 

PollRemoveTest test failure 

io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

PollRemoveTest.java 79 line

**Comment by normanmaurer** [comment]
@cmonkey what os / kernel you are using ?

**Comment by cmonkey** [comment]
> @cmonkey what os / kernel you are using ?
uname -a 
Linux dev-mchine 5.9.2-arch1-1 #1 SMP PREEMPT Thu, 29 Oct 2020 17:01:28 +0000 x86_64 GNU/Linux

limit 
cputime         unlimited
filesize        unlimited
datasize        unlimited
stacksize       8MB
coredumpsize    unlimited
memoryuse       unlimited
maxproc         127203
descriptors     1024
memorylocked    32MB
addressspace    unlimited
maxfilelocks    unlimited
sigpending      127203
msgqueue        819200
nice            0
rt_priority     0
rt_time         unlimited

**Comment by normanmaurer** [comment]
I will check... what happens if you add a "small sleep" before we bind again ?
