### ISSUE TITLE
IOUring uses more heap memory than Epoll transport

### ISSUE THREAD

**Issue by amizurov** [netty/netty-incubator-transport-io_uring#61]
We have integrated IOUring into our communication layer as an experimental feature, after which I did some comparison test between `EPOLL` and `IOURING` I want to share some info.

I ran small load test and noticed that `IOURING` transport uses more heap memory than `EPOLL` with same load.

1) EPOLL 
![image](https://user-images.githubusercontent.com/8257855/104817858-18f2ac00-5835-11eb-8708-f6925a9acf08.png)

2) IOURING
![image](https://user-images.githubusercontent.com/8257855/104817824-cc0ed580-5834-11eb-8999-a7fa4be408ef.png)

After that I decided to use the async-profiler and check memory allocation for both transport. After briefly comparing two flame graphs I found that `io.netty.incubator.channel.uring.IOUringSubmissionQueue#setData` allocate allot of `java.lang.Integer` and `java.lang.Long`.

I think it's because we use 
```
            logger.trace("UserDataField: {}", userData);
            logger.trace("BufferAddress: {}", bufferAddress);
            logger.trace("Length: {}", length);
            logger.trace("Offset: {}", offset);
```

without check `logger.isTraceEnabled()` , since we pass a primitive and the method takes an Object as parameter, we allocate the new object each time.

**OS version**: 5.9.0-050900-generic #202010112230 SMP Sun Oct 11 22:34:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**Java version**: openjdk version "11.0.9.1" 2020-11-04

**Comment by normanmaurer** [comment]
Good catch... want to provide a PR?

**Comment by amizurov** [comment]
> Good catch... want to provide a PR?

I'll try to do it if nothing special needs for develop requirement.

**Comment by njhill** [comment]
Nice one @amizurov! I wonder if this will make a difference to the benchmark numbers..

**Comment by amizurov** [comment]
> Nice one @amizurov! I wonder if this will make a difference to the benchmark numbers..

I'm not sure that only this factor affected to heap allocation, maybe `visualvm` attach also has impact, but i checked an allocation profiler after fix and now it looks similar for both `EPOLL` and `IOURING` transports.

I do not think that my experiment is clean and clearly indicates this, but still `IOURING` now is looks better 😄 .

1) IOURING 
![image](https://user-images.githubusercontent.com/8257855/104838307-3bcf9f80-58cb-11eb-8b93-5fa4e2a00805.png)
2) EPOLL
![image](https://user-images.githubusercontent.com/8257855/104838313-4ab65200-58cb-11eb-9cb8-0d07e7dc6928.png)
