### ISSUE TITLE
blocking eventfd in IOUringEventLoop.java

### ISSUE THREAD

**Issue by HowHsu** [netty/netty-incubator-transport-io_uring#84]
Hi there,
I found there is a blocking eventfd in IOUringEventLoop.java, since I'm not familiar with java and netty, could any tell me what is it for?
Here the thing  is an eventfd without O_NONBLOCK flag will trigger io-wq threads in io_uring. Is reading/writing for this eventfd  high frequency operations?  If yes, then in systems that has few cpu resources, it may affect the service quality, I guess. 

Regards,
Hao

**Comment by chrisvest** [comment]
Hi Hao,
When the event loop has nothing to do - either no work has been lined up, or no previously submitted IO requests have completed yet - then the thread needs to sleep in a way that it can be woken up when either condition flips. The eventfd is used for that.

**Comment by HowHsu** [comment]
Hi Chrisvest,
Would a nonblocking eventfd work well? If yes, then I think it's better for cpu-scarce system.
The difference between reading/writing blocking and nonblocking eventfd is whether to do the work in the io-wq kernel threads or inline. For fd type like eventfd, I don't see the difference.

Thanks,
Hao

**Comment by njhill** [comment]
@HowHsu it's not really blocking IO on the kernel side, it just has blocking semantics. It means we can take advantage of iouring's FAST_POLL feature which combines a poll + read in a single syscall, otherwise an additional read would be needed every time the eventfd triggers. (see https://github.com/netty/netty-incubator-transport-io_uring/commit/cf60172e6461d9cbfa39b4a7338afab7177c9b2a)

**Comment by HowHsu** [comment]
@njhill yes, in io_uring kernel side, they are both nonblocking. But currently it seems that there is some issue when reading an eventfd without O_NONBLOCK being set, I would figure it out. Btw, FAST_POLL feature will be leveraged no matter an eventfd is marked O_NONBLOCK or not, I think.
